// IMPORTANT! This file is autogenerated by the `type-safe-next-routes` 
// package. You should _not_ update these types manually...

declare module "next-type-safe-routes" {
  type Query = { [key: string]: any };
  export type TypeSafePage = "/administration/administrateurs" | { route: "/administration/administrateurs", query?: Query } | "/administration/emails" | { route: "/administration/emails", query?: Query } | "/administration" | { route: "/administration", query?: Query } | "/administration/seances" | { route: "/administration/seances", query?: Query } | { route: "/administration/seances/modeles/[id]/edition", params: { "id": string | number }, query?: Query } | "/administration/seances/modeles/creation" | { route: "/administration/seances/modeles/creation", query?: Query } | "/administration/utilisateurs" | { route: "/administration/utilisateurs", query?: Query } | "/backoffice" | { route: "/backoffice", query?: Query } | "/new" | { route: "/new", query?: Query } | "/newConnexion" | { route: "/newConnexion", query?: Query } | "/redirection" | { route: "/redirection", query?: Query };
  export type TypeSafeApiRoute = { route: "/api/auth", path: string, query?: Query } | { route: "/api/trpc/[trpc]", params: { "trpc": string | number }, query?: Query };
  export const getPathname: (typeSafeUrl: TypeSafePage | TypeSafeApiRoute) => string;
  export const getRoute: (typeSafeUrl: TypeSafePage | TypeSafeApiRoute) => string;
}
