-- AlterTable
ALTER TABLE `other_payment` ADD COLUMN `type` ENUM('CASH', 'HELLO_ASSO', 'CHECK', 'TRANSFER', 'AUTOMATIC_DEBIT') NOT NULL DEFAULT 'CASH';
ALTER TABLE `other_payment` ALTER COLUMN `type` DROP DEFAULT;
