name: CI

on:
  push:
    branches:
      - master
      - development
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
    # - run: npm run lint
      - run: npm run generate-favicons
      - run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          UPDATE_TOKEN: ${{secrets.UPDATE_TOKEN}}
        run: bash scripts/notify-update-production.sh
